export enum DeliveryMethod {
  BUS = 'BUS',
  TAXI = 'TAXI',
}

export enum DeliveryLocation {
  // 20 Dzongkhags
  BUMTHANG = 'BUMTHANG',
  CHUKHA = 'CHUKHA',
  DAGANA = 'DAGANA',
  GASA = 'GASA',
  HAA = 'HAA',
  LHUNTSE = 'LHUNTSE',
  MONGAR = 'MONGAR',
  PARO = 'PARO',
  PEMAGATSHEL = 'PEMAGATSHEL',
  PUNAKHA = 'PUNAKHA',
  SAMDRUP_JONGKHAR = 'SAMDRUP_JONGKHAR',
  SAMTSE = 'SAMTSE',
  SARPANG = 'SARPANG',
  THIMPHU = 'THIMPHU',
  TRASHIGANG = 'TRASHIGANG',
  TRASHIYANGTSE = 'TRASHIYANGTSE',
  TRONGSA = 'TRONGSA',
  TSIRANG = 'TSIRANG',
  WANGDUE_PHODRANG = 'WANGDUE_PHODRANG',
  ZHEMGANG = 'ZHEMGANG',
  
  // 4 Thromdes
  THIMPHU_THROMDE = 'THIMPHU_THROMDE',
  GELEPHU_THROMDE = 'GELEPHU_THROMDE',
  SAMDRUP_JONGKHAR_THROMDE = 'SAMDRUP_JONGKHAR_THROMDE',
  // Note: 4th Thromde to be confirmed - placeholder for now
  PHUENTSHOLING_THROMDE = 'PHUENTSHOLING_THROMDE',
}

